#!/bin/sh

# Analog Recyling - 79 VJ loops in BSD licence
# http://www.archive.org/details/ANALOG_RECYCLING_VJ_LOOPS

wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/licenseREADME.txt
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_ARROW_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_ARROW_3.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_ARROW_4.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_BALLS_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_BALLS_2.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_BALLS_3.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_BLUE_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_BLUE_2.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_BLUE_3.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_BLUE_4.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_CILINDER_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_CITY_CHINA_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_CITY_CHINA_2.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_COLOUR_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_COLOUR_2.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_COLOUR_3.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_COLOUR_4.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_COLOUR_5.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_FIRE_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_FXCOOL_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_FXCOOL_2.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_FXCOOL_3.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_FXCOOL_4.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_FXCOOL_5.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_FXCOOL_6.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_FXCOOL_7.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_FXCOOL_8.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_FXCOOL_9.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRAFX_GLO_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRAFX_GLO_2.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRAFX_GLO_3.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRAFX_GLO_4.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRAFX_GLO_5.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRAFX_GLO_6.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRAFX_GLO_7.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRAFX_KNOBS.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRAFX_PURPLE_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRAFX_PURPLE_2.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRAFX_PURPLE_3.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRAFX_PURPLE_4.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRAFX_TUN_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRAFX_TUN_2.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRUNGE_GUITARS.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRUNGE_MATRIXX.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRUNGE_PILOT.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRUNGE_REDDANCE.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRUNGE_SMPTESUN.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_GRUNGE_TV.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_HAL_ROUND.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_HEART_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_HEART_2.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_INCONTROL.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_KALEI_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_KALEI_2.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_LINES_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_LOGO_GLO.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_LOGO_SMPTE.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_LOGO_TEEP.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_RED_BLUE.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_ROBOT_FIRE_1.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_ROBOT_FIRE_2.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_ROBOT_FIRE_3.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_ROBOT_FIRE_4.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_ROBOT_MASCOT.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_ROBOT_RADIAL.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_SL1200.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_SL1200_SCRATCH.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_SPEEDCAR.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_STARS.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_STARS_ROBOT.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_WORDFEELDANCE.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_WORD_BELIEVE.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_WORD_CLUB.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_WORD_FEELMUSIC.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_WORD_LOVEDDANCE.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_WORD_LOVEMUSIC.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_WORD_MIX.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_WORD_YOUFEEL.mov
wget -c http://www.archive.org/download/ANALOG_RECYCLING_VJ_LOOPS/AR_XPLO_CUBE.mov
