#!/bin/sh

# Analog Recyling 2 - 79 VJ Loops in BSD License
# http://www.archive.org/details/Analog_Recycling_VJ_Loops_II

wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_8BIT_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_8BIT_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_8BIT_3.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_8BIT_4.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_8BIT_5.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_ARROWLITE.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_ARROWSINE_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_ARROWSINE_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_BLACKDATA_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_BLACKDATA_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_BLACKDATA_3.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_BLOKSTREAK_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_BLOKSTREAK_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_BLOKSTREAK_3.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_BLOKSTREAK_4.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_BLOX_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_BLOX_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_BOUGIE_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_BOUGIE_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_BOUGIE_3.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_BOUGIE_4.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_CHINACITY_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_CHINACITY_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_COLORCIRC_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_DATA_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_DATA_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_FLARE_BLUE.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_FLARE_GREEN.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_FLARE_RED.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_GRLL_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_GLITCH.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_GRLL_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_GRLL_3.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_GRLL_4.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_HAL_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_HAL_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_HAL_3.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_HART_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_HART_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_HART_3.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_HART_4.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_HART_5.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_LIQUID_BLUE_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_LIQUID_BLUE_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_LIQUID_RED.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_LITENING_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_LITENING_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_PURRLINE_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_RBLINE_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_RBLINE_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_RBLINE_3.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_RBLINE_4.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_RBLINE_5.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_RBLINE_6.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_RBSTREAX_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_RBSTREAX_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_REDBLAXSYM.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_REDDATA_1.MOV
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_REDDATA_2.MOV
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_REDDATA_3.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_RICOTEK.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_SINE_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_SINE_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_STREAK_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_STREAK_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_TRENSLINE_1.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_TRENSLINE_2.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_TRENSLINE_3.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_TRENSLINE_4.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_TRENSLINE_5.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_TURNMANGA.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/AR_WAVEE.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/Ar_8BIT_10.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/Ar_8BIT_11.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/Ar_8BIT_12.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/Ar_8BIT_6.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/Ar_8BIT_7.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/Ar_8BIT_8.mov
wget -c http://ia340929.us.archive.org/3/items/Analog_Recycling_VJ_Loops_II/Ar_8BIT_9.mov
